env: "dev"
postgres:
  host: "pg.zzxcloud.cn"
  dbname: "uroborus"
  port: 5432
  user: "root"
  passwd: "root"
  batchSize: 3000

root: "./user/uroborus"
registry:
  url: "https://registry.hub.docker.com"
docker:
  host: "tcp://121.196.214.245:22375"
kafka:
  addrs:
    - "121.196.214.245:9092"
  chanSize: 100000